### ISSUE TITLE
Awesome work... Looking for a job?

### ISSUE THREAD

**Issue by msolnik** [knilink/job-hunting#1]
I saw your work in the language-server repo and it was very impressive. My company is looking for someone with your skillset (JS/TS engineering + reverse engineering). If interested let me know the best way to get in touch.

**Comment by knilink** [comment]
Hi @mspublic, thanks for reaching out and for your kind words about my work. The best way to get in touch with me would be via email at esurllink@gmail.com. Looking forward to connecting with you soon.
